name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
  dist:
    description: 'folder dist'
    requred: true
outputs:
  file: 
    description: "Archive"
    value: ${{ steps.archive.outputs.archive }}
runs:
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo os ${{runner.os}}
      shell: bash
    - name: Archive
      id: archive
      run: |
        pushd ${{ inputs.dist }}
        zip -r ${{ inputs.dist }}.zip *
        ARCHIVE=dist.zip
        popd
        echo "::set-output name=archive::$(echo $ARCHIVE)"
    - run: ls . && ls ./${{ inputs.dist }}/
