name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
  dist:
    description: 'folder dist'
    requred: true
outputs:
  file: 
    description: "fileexample"
    value: ${{ steps.fileexample.outputs.test }}
runs:
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo os ${{runner.os}}
      shell: bash
    - name: Archive
      run: |
        pushd ${{ inputs.dist }}
        zip -r ${{ inputs.dist }}.zip *
        popd
    - run: ls . && ls ./${{ inputs.dist }}/
