name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
  file:
    description: 'some files'
    required: true 
outputs:
  file: 
    description: "fileexample"
    value: ${{ steps.fileexample.outputs.test }}
runs:
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo os ${{runner.os}}
      shell: bash
    - id: fileexample
      run: |
        mkdir /test/
        cat test.sh
        chmod 777 test.sh
        ls .
        cp ${{ inputs.file }} /test/tested.sh
        ls /test/
        cat /test/tested.sh
        test=$(echo `cat /test/tested.sh`)
        echo $test
      shell: bash
