name: 'Hello World'
description: 'Greet someone'
inputs:
  dist:
    description: 'folder dist'
    requred: true
  version:
    description: 'Version'
    requred: false
    default: ''
outputs:
  archive: 
    description: "Archive"
    value: ${{ steps.archive.outputs.archive }}
  s3:
    description: "S3 catalog"
    value: ${{ steps.s3.outputs.s3 }}
runs:
  using: "composite"
  steps: 
    - name: Archive
      id: archive
      run: |
        pushd ${{ inputs.dist }}
        zip -r ${{ inputs.dist }}.zip *
        ARCHIVE=${{ inputs.dist }}.zip
        popd
        echo "::set-output name=archive::$(echo $ARCHIVE)"
      shell: bash
    - run: ls . && ls ./${{ inputs.dist }}/
      shell: bash
    - name: Get the version
      run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/^v-\?//g')" >> $GITHUB_ENV
      shell: bash
    - name: Prepare S3 upload if Vesion exists
      #if: ${{ inputs.version }} == ''
      id: s3
      run: |
        mkdir s3 
        [[ "${{ inputs.version }}" == "" ]] && distname='latest' || distname=${{ inputs.version }}
        mv ${{ inputs.dist }}/${{ inputs.dist }}.zip s3/$distname.zip
        mv ${{ inputs.dist }} s3/$distname
        S3=s3
        echo "::set-output name=s3::$(echo $S3)"
      shell: bash

     
