name: 'Hello World'
description: 'Greet someone'
inputs:
  dist:
    description: 'folder dist'
    requred: true
outputs:
  archive: 
    description: "Archive"
    value: ${{ steps.archive.outputs.archive }}
  s3:
    description: "S3 catalog"
    value: ${{ steps.s3.outputs.s3 }}
runs:
  using: "composite"
  steps: 
    - name: Archive
      id: archive
      run: |
        pushd ${{ inputs.dist }}
        zip -r ${{ inputs.dist }}.zip *
        ARCHIVE=dist.zip
        popd
        echo "::set-output name=archive::$(echo $ARCHIVE)"
      shell: bash
    - run: ls . && ls ./${{ inputs.dist }}/
      shell: bash
    - name: Prepare S3 upload
      id: s3
      run: |
        mkdir s3
        mv ${{ inputs.dist }}/${{ inputs.dist }}.zip s3/latest.zip
        mv dist s3/latest
        S3=s3
        echo "::set-output name=s3::$(echo $S3)"
      shell: bash
