name: 'Zipping folder and prepare to upload'
description: 'no description'
inputs:
  inputdir:
    description: 'folder to upload'
    requred: true
  archivename:
    description: 'name for archive'
    requred: false
    default: 'archive'
outputs:
  archive: 
    description: "Archive"
    value: ${{ steps.archive.outputs.archive }}
runs:
  using: "composite"
  steps: 
    - name: Archive
      id: archive
      run: |
        pushd ${{ inputs.inputdir }}
        zip -r ${{ inputs.archivenane }}.zip *
        popd
        ARCHIVENAME=${{inputs.archivenane}}
        echo "::set-output name=archive::$(echo $ARCHIVENAME)"
      shell: bash
    - name: REPORT
      run: echo "REPORT" && ls ./${{ inputs.inputdir }}/
      shell: bash
